services:
  mariadb:
    image: mariadb:latest
    container_name: grp1-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: sua_senha_root_segura
      MARIADB_DATABASE: embrapac
      MARIADB_USER: agenor
      MARIADB_PASSWORD: admin123
    ports:
      - "13306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-users.sql:/docker-entrypoint-initdb.d/init-users.sql:ro
    # networks:
    #   - default_network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  flyway:
    image: flyway/flyway:latest
    command: migrate
    container_name: grp1-flyway
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/embrapac
      FLYWAY_USER: agenor
      FLYWAY_PASSWORD: admin123
    # networks:
    #   - default_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: grp1-mosquitto
    restart: unless-stopped
    ports:
      - "11883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    # networks:
    #   - default_network

  backend-server:
    build:
      context: ./mqtt-ingestor
    container_name: grp1-mqtt-ingestor
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      mosquitto:
        condition: service_started
    environment:
      EXECUTION_MODE: compose
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      MQTT_CLIENT_ID: grp1-mqtt-backend-server
      MQTT_SUB_COUNT: embrapac/edge/count
      MQTT_SUB_CBELT: embrapac/edge/cbelt
      MQTT_PUB_CBELT_STATUS: embrapac/edge/cbelt/status
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${DB_USER:?DB_USER environment variable is required}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD environment variable is required}
      DB_NAME: embrapac

  influxdb:
    image: influxdb:1.8
    container_name: grp1-influxdb
    ports:
      - "18086:8086"
    environment:
      - INFLUXDB_DB=iot_data
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf_pass
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: grp1-telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grp1-grafana
    ports:
      - "13000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  influxdb_data:
  grafana_data:
  mariadb_data:
    driver: local

# networks:
#   default_network:
#     name: grp01_default_network
#     driver: bridge
