{
 "title": "Embrapac KPIs",
 "description": "Dashboard de KPIs do sistema Embrapac IIoT",
 "tags": [
  "embrapac",
  "iiot",
  "mcu"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da Esteira",
   "type": "stat",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "embrapac",
     "rawSql": "SELECT state\nFROM embrapac.conveyorbelt\nORDER BY updated_at DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Countagem Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"positive_sample_count\") FROM \"mcu_samples\"\nWHERE $timeFilter\nGROUP BY \"mcu_class\""
    }
   ]
  },
  {
   "title": "Contagem G",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"positive_sample\") FROM \"mcu_samples\"\nWHERE \"mcu_class\" = 'Grande' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Contagem M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"positive_sample\") FROM \"mcu_samples\"\nWHERE \"mcu_class\" = 'Media' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Contagem P",
   "type": "stat",
   "description": "Contagem de caixas pequenas",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"positive_sample\") FROM \"mcu_samples\"\nWHERE \"mcu_class\" = 'Pequena' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Precisão de Detecção Geral",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"positive_sample\") * 100 FROM \"mcu_samples\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Precisão de detecção: Caixa Grande",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"positive_sample\") * 100 FROM \"mcu_samples\" WHERE $timeFilter AND \"mcu_class\" = 'Grande'"
    }
   ]
  },
  {
   "title": "Precisão de Detecção: Caixa Média",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"positive_sample\") * 100 FROM \"mcu_samples\" WHERE $timeFilter AND \"mcu_class\" = 'Media'"
    }
   ]
  },
  {
   "title": "Precisão de Detecção: Caixa Pequena",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"positive_sample\") * 100 FROM \"mcu_samples\" WHERE $timeFilter AND \"mcu_class\" = 'Pequena'"
    }
   ]
  }
 ]
}