[agent]
  interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["embrapac/#"]
#  data_format = "value"
#  data_type = "float"   # para valores numéricos simples
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "mcu_samples"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "class_match"
      type = "bool"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "mcu_ts_in_range"
      type = "bool"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "mcu_class"
      type = "string"

# Processor Starlark: deriva campo "positive_sample" (1 ou 0)
[[processors.starlark]]
  namepass = ["mcu_samples"]
  source = '''
def apply(metric):
    cm = metric.fields.get("class_match", False)
    ts = metric.fields.get("mcu_ts_in_range", False)
    metric.fields["positive_sample"] = 1 if (cm == True and ts == True) else 0
    return metric
'''

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "iot_data"
  username = "telegraf"
  password = "telegraf_pass"
